### ISSUE TITLE
Silently ignores any b!device commands if the bot doesn't have Manage Messages permission

### ISSUE THREAD

**Issue by nyuszika7h** [m1stadev/AutoTSS#4]
Took me a while to figure this one out.

**Comment by marijuanARM** [comment]
the Manage Messages permission is something AutoTSS requires, as user's device information (such as their ECID) could unintentionally be leaked when adding a device (which AutoTSS prevents by deleting the user's input, but if it can't do that, then that's a big issue). I'll implement handling, so that if AutoTSS doesn't have the Manage Messages permission, it'll notify the server owner asking for the permission.

**Comment by m1stadev** [comment]
Update: Implemented this [here](https://github.com/m1stadev/AutoTSS/blob/f38b252725c1cc94767611659a48991853895dd5/cogs/events.py#L166).
